xqb/notes/urls.py
from django.urls import path

from notes.views import (
    NoteCreateView,
    NoteDeleteView,
    NoteListView,
    NoteUpdateView,
    SearchNotesView,
    ShowNoteView,
)


app_name = 'notes'
urlpatterns = [
    path('<int:notebook_pk>/', NoteListView.as_view(), name='note-list'),
    path('create/', NoteCreateView.as_view(), name='note-create'),
    path('<int:notebook_pk>/create/', NoteCreateView.as_view(), name='note-create'),
    path('<int:notebook_pk>/<int:note_pk>/delete/', NoteDeleteView.as_view(), name='note-delete'),
    path('<int:notebook_pk>/<int:note_pk>/update/', NoteUpdateView.as_view(), name='note-update'),
    path('ajax/show-note/', ShowNoteView.as_view(), name='show-note'),
    path('ajax/search/<int:notebook_pk>/<str:by>/', SearchNotesView.as_view(), name='search-notes'),
]

xqb/xqb/urls.py
from django.contrib import admin
from django.urls import include, path
from django_js_reverse.views import urls_js

from pages.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('users.urls')),
    path('jsreverse/', urls_js, name='js_reverse'),
    path('martor/', include('martor.urls')),
    path('notes/', include('notes.urls')),
    path('notebooks/', include('notebooks.urls')),
]

xqb/notes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from martor.models import MartorField
from taggit.managers import TaggableManager
from taggit.models import Tag

from notebooks.models import Notebook


class Note(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=255)
    description = MartorField()
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)
    notebook = models.ForeignKey(Notebook, on_delete=models.CASCADE)
    tags = TaggableManager(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class MyTag(models.Model):
    tag = models.OneToOneField(Tag, on_delete=models.CASCADE)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)


@receiver(post_save, sender=Tag)
def create_tag(sender, instance, created, **kwargs):
    if created:
        MyTag.objects.create(tag=instance)


@receiver(post_save, sender=Tag)
def save_tag(sender, instance, **kwargs):
    instance.mytag.save()

xqb/notes/forms.py
from django import forms

from notebooks.models import Notebook
from notes.models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'description', 'notebook', 'tags']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['notebook'].queryset = Notebook.objects.filter(added_by=user)

xqb/notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    TemplateView,
    UpdateView,
)
from django.shortcuts import get_object_or_404
from django.urls import reverse

from notes.forms import NoteForm
from notes.models import Note


class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    form_class = NoteForm

    def form_valid(self, form):
        form.instance.added_by = self.request.user
        form.instance.save()
        form.save(commit=False)
        form.save_m2m()
        for tag in form.instance.tags.all():
            tag.mytag.added_by = self.request.user
            tag.mytag.save()
        return super().form_valid(form)

    def get_initial(self):
        return {'notebook': self.kwargs.get('notebook_pk')}

    def get_success_url(self):
        return reverse(
            'notes:note-list', kwargs={'notebook_pk': self.request.POST.get('notebook')}
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class NoteListView(LoginRequiredMixin, ListView):
    model = Note
    context_object_name = 'notes'

    def get_queryset(self):
        return Note.objects.filter(
            added_by=self.request.user, notebook=self.kwargs['notebook_pk']
        )

    def get_context_data(self, *args, **kwargs):
        ctx = {'notebook': self.kwargs['notebook_pk']}
        context = super().get_context_data(*args, **kwargs)
        context.update(ctx)
        return context


class NoteUpdateView(LoginRequiredMixin, UpdateView):
    model = Note
    form_class = NoteForm
    template_name_suffix = '_update_form'

    def get_object(self):
        return get_object_or_404(
            Note, pk=self.kwargs['note_pk'], added_by=self.request.user
        )

    def get_success_url(self):
        return reverse(
            'notes:note-list', kwargs={'notebook_pk': self.request.POST.get('notebook')}
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class NoteDeleteView(LoginRequiredMixin, DeleteView):
    model = Note

    def get_object(self):
        return get_object_or_404(
            Note, pk=self.kwargs['note_pk'], added_by=self.request.user
        )

    def get_success_url(self):
        return reverse(
            'notes:note-list', kwargs={'notebook_pk': self.kwargs['notebook_pk']}
        )


class ShowNoteView(TemplateView):
    template_name = 'notes/note_detail.html'

    def get_context_data(self, *args, **kwargs):
        try:
            pk = int(self.request.GET.get('pk'))
        except ValueError:
            raise Http404
        note = Note.objects.get(added_by=self.request.user, pk=pk)
        context = super().get_context_data(*args, **kwargs)
        context['note'] = note
        return context


class SearchNotesView(TemplateView):
    template_name = 'notes/searched_notes.html'

    def get_context_data(self, *args, **kwargs):
        search_query = self.request.GET.get('query')
        notebook = self.kwargs['notebook_pk']
        by = self.kwargs['by']
        if by == 'all':
            notes = Note.objects.filter(
                Q(title__icontains=search_query)
                | Q(description__icontains=search_query)
                | Q(tags__name__in=[search_query]),
                added_by=self.request.user,
                notebook=notebook,
            ).distinct()
        elif by == 'title':
            notes = Note.objects.filter(
                title__icontains=search_query,
                added_by=self.request.user,
                notebook=notebook,
            ).distinct()
        elif by == 'description':
            notes = Note.objects.filter(
                description__icontains=search_query,
                added_by=self.request.user,
                notebook=notebook,
            ).distinct()
        elif by == 'tags':
            notes = Note.objects.filter(
                tags__name__icontains=search_query,
                added_by=self.request.user,
                notebook=notebook,
            ).distinct()
        else:
            raise Http404
        context = super().get_context_data(*args, **kwargs)
        context['notes'] = notes
        return context

xqb/notes/templates/notes/note_confirm_delete.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'notes/css/note_confirm_delete.css' %}">
{% endblock %}

{% block content %}
<div class="form-wrapper">
  <div class="form-header">
    Delete note
  </div>
  <form method="POST">
    {% csrf_token %}
    <div class="field-wrapper">
      <p>Are you sure you want to delete note "{{ object }}"?</p>
    </div>
    <div class="submit-button">
      <input type="submit" value="Confirm">
      <a href="{% url 'notes:note-list' object.notebook.pk %}">No, go back</a>
    </div>
  </form>
</div>
{% endblock %}

xqb/notes/templates/notes/note_detail.html
{% load martortags %}

<h3>{{ note.title }}</h3>
<div class="tags">
  {% for tag in note.tags.all %}
  <div class="badge">
    {{ tag }}
  </div>
  {% endfor %}
</div>
<div class="description martor-preview">
  {{ note.description|safe_markdown }}
</div>

xqb/notes/templates/notes/note_form.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap4 %}

{% block css %}
{% bootstrap_css %}
<link type="text/css" rel="stylesheet" href="{% static 'notes/css/note_form.css' %}">
<link type="text/css" media="all" rel="stylesheet" href="{% static 'plugins/css/ace.min.css' %}" />
<link type="text/css" media="all" rel="stylesheet" href="{% static 'plugins/css/resizable.min.css' %}" />
<link type="text/css" media="all" rel="stylesheet" href="{% static 'martor/css/martor.bootstrap.min.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'notes/css/tags_input.css' %}" />
{% endblock %}

{% block js %}
{% bootstrap_javascript %}
<script type="text/javascript" src="{% static 'notes/js/tagsView.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/typo.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/spellcheck.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
<script type="text/javascript" src="{% static 'martor/js/martor.bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'notes/js/tagsInput.js' %}"></script>
{% endblock %}

{% block content %}
<div class="form-wrapper">
  <div class="form-header">
    Create a new note
  </div>
  <form method="POST">
    {% csrf_token %}
    <div class="field-wrapper">
      <div class="title">
        {{ form.title.label_tag }}
        {{ form.title }}
        {{ form.title.errors }}
      </div>
      <div class="description">
        {{ form.description.label_tag }}
        {{ form.description }}
        {{ form.description.errors }}
      </div>
      <div class="notebook">
        {{ form.notebook.label_tag }}
        {{ form.notebook }}
        {{ form.notebook.errors }}
      </div>
      <div class="tags">
        {{ form.tags.label_tag }}
        {{ form.tags }}
        {{ form.tags.errors }}
      </div>
    </div>
    <div class="submit-button">
      <input type="submit" value="Submit">
    </div>
  </form>
</div>
{% endblock %}

xqb/notes/templates/notes/note_list.html
{% extends 'base.html' %}

{% load static %}
{% load martortags %}
{% load get_note_ago %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'notes/css/note_list.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'notes/css/note_detail.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'notes/css/search_box.css' %}">
<link type="text/css" media="all" rel="stylesheet" href="{% static 'plugins/css/ace.min.css' %}" />
<link type="text/css" media="all" rel="stylesheet" href="{% static 'plugins/css/semantic.min.css' %}" />
<link type="text/css" media="all" rel="stylesheet" href="{% static 'plugins/css/resizable.min.css' %}" />
<link type="text/css" media="all" rel="stylesheet" href="{% static 'martor/css/martor.min.css' %}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% url 'js_reverse' %}"></script>
<script type="text/javascript" src="{% static 'notes/js/searchNotes.js' %}"></script>
<script type="text/javascript" src="{% static 'notes/js/showNote.js' %}"></script>
<script type="text/javascript" src="{% static 'notes/js/searchBox.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
<script type="text/javascript" src="{% static 'martor/js/martor.min.js' %}"></script>
<script>
  $(document).ready(function() {
    $('pre').each(function(i, block){
      hljs.highlightBlock(block);
    });    
  });
</script>
{% endblock %}

{% block content %}
{% if notes %}
<div class="notes-container">
  <div class="top-container">
      <div class="search-bar">
          <input id="search-box" type="text" name="q" placeholder="Search notes">
          <span>&#xf2f5;</span>
          <div class="by">
              <span class="selected">All</span>
              <div class="options" by="all">
                  <div id="all" class="option">All</div>
                  <div id="title" class="option">Title</div>
                  <div id="description" class="option">Description</div>
                  <div id="tags" class="option">Tags</div>
              </div>
          </div>
      </div>
      <div class="new-note">
          <a href="{% url 'notes:note-create' notebook_pk=notebook %}">&#xf381;</a>
      </div>
  </div>
  <div class="notes">
    {% for note in notes %}
      <div id="{{ note.pk }}" class="note">
        <div class="note-ago">
          {% note_ago user note %}
        </div>
        <div class="note-wrapper">
          <div class="note-title">
            {{ note.title }}
          </div>
          <div class="note-description martor-preview">
            {{ note.description|truncatechars:255 }}
          </div>
          <div class="tags">
            {% for tag in note.tags.all %}
            <div class="badge">
              {{ tag }}
            </div>
            {% endfor %}
          </div>
          <div class="actions">
            <a href="{% url 'notes:note-update' notebook_pk=note.notebook.pk note_pk=note.pk %}">Update</a>
            <a href="{% url 'notes:note-delete' notebook_pk=note.notebook.pk note_pk=note.pk %}">Delete</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% else %}
<div class="information">
  <div class="information-header">
    Info
  </div>
  <div class="information-wrapper">
    No notes yet.<br>
    <a href="{% url 'notes:note-create' notebook_pk=notebook %}">Create your first note!</a>
  </div>
</div>
{% endif %}
<div class="note-container">
</div>
{% endblock %}

xqb/notes/templates/notes/note_update_form.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap4 %}

{% block css %}
{% bootstrap_css %}
<link type="text/css" rel="stylesheet" href="{% static 'notes/css/note_form.css' %}">
<link type="text/css" media="all" rel="stylesheet" href="{% static 'plugins/css/ace.min.css' %}" />
<link type="text/css" media="all" rel="stylesheet" href="{% static 'plugins/css/semantic.min.css' %}" />
<link type="text/css" media="all" rel="stylesheet" href="{% static 'plugins/css/resizable.min.css' %}" />
<link type="text/css" media="all" rel="stylesheet" href="{% static 'martor/css/martor.min.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'notes/css/tagsinput.css' %}" >
{% endblock %}

{% block js %}
{% bootstrap_javascript %}
<script type="text/javascript" src="{% static 'notes/js/tagsView.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
<script type="text/javascript" src="{% static 'martor/js/martor.min.js' %}"></script>
<script type="text/javascript" src="{% static 'notes/js/tagsinput.js' %}"></script>
{% endblock %}

{% block content %}
<div class="form-wrapper">
  <div class="form-header">
    Update note
  </div>
  <form method="POST">
    {% csrf_token %}
    <div class="field-wrapper">
      <div class="title">
        {{ form.title.label_tag }}
        {{ form.title }}
        {{ form.title.errors }}
      </div>
      <div class="description">
        {{ form.description.label_tag }}
        {{ form.description }}
        {{ form.description.errors }}
      </div>
      <div class="notebook">
        {{ form.notebook.label_tag }}
        {{ form.notebook }}
        {{ form.notebook.errors }}
      </div>
      <div class="tags">
        {{ form.tags.label_tag }}
        {{ form.tags }}
        {{ form.tags.errors }}
      </div>
    </div>
    <div class="submit-button">   
      <input type="submit" value="Submit">
    </div>
</form>
</div>
{% endblock %}

xqb/notes/templates/notes/searched_notes.html
{% load martortags %}
{% load get_note_ago %}

{% for note in notes %}
<div id="{{ note.pk }}" class="note">
  <div class="note-ago">
    {% note_ago user note %}
  </div>
  <div class="note-wrapper">
    <div class="note-title">
      {{ note.title }}
    </div>
    <div class="note-description martor-preview">
      {{ note.description|truncatechars:255|safe_markdown }}
    </div>
    <div class="tags">
      {% for tag in note.tags.all %}
      <div class="badge">
        {{ tag }}
      </div>
      {% endfor %}
    </div>
    <div class="actions">
      <a href="{% url 'notes:note-update' notebook_pk=note.notebook.pk note_pk=note.pk %}">Update</a>
      <a href="{% url 'notes:note-delete' notebook_pk=note.notebook.pk note_pk=note.pk %}">Delete</a>
    </div>
  </div>
</div>
{% endfor %}