xqb/notebooks/urls.py
from django.urls import path

from notebooks.views import (
    NotebookCreateView,
    NotebookDeleteView,
    NotebookListView,
    NotebookUpdateView,
    SearchNotebooksView,
)


app_name = 'notebooks'
urlpatterns = [
    path('', NotebookListView.as_view(), name='notebook-list'),
    path('create/', NotebookCreateView.as_view(), name='notebook-create'),
    path('<int:notebook_pk>/delete/', NotebookDeleteView.as_view(), name='notebook-delete'),
    path('<int:notebook_pk>/update/', NotebookUpdateView.as_view(), name='notebook-update'),
    path('ajax/search/', SearchNotebooksView.as_view(), name='search-notebooks'),
]

xqb/notes/urls.py
from django.urls import path

from notes.views import (
    NoteCreateView,
    NoteDeleteView,
    NoteListView,
    NoteUpdateView,
    SearchNotesView,
    ShowNoteView,
)


app_name = 'notes'
urlpatterns = [
    path('<int:notebook_pk>/', NoteListView.as_view(), name='note-list'),
    path('create/', NoteCreateView.as_view(), name='note-create'),
    path('<int:notebook_pk>/create/', NoteCreateView.as_view(), name='note-create'),
    path('<int:notebook_pk>/<int:note_pk>/delete/', NoteDeleteView.as_view(), name='note-delete'),
    path('<int:notebook_pk>/<int:note_pk>/update/', NoteUpdateView.as_view(), name='note-update'),
    path('ajax/show-note/', ShowNoteView.as_view(), name='show-note'),
    path('ajax/search/<int:notebook_pk>/<str:by>/', SearchNotesView.as_view(), name='search-notes'),
]

xqb/xqb/urls.py
from django.contrib import admin
from django.urls import include, path
from django_js_reverse.views import urls_js

from pages.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('users.urls')),
    path('jsreverse/', urls_js, name='js_reverse'),
    path('martor/', include('martor.urls')),
    path('notes/', include('notes.urls')),
    path('notebooks/', include('notebooks.urls')),
]

xqb/notebooks/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Notebook(models.Model):
    slug = models.SlugField()
    name = models.CharField(max_length=255)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

xqb/notes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from martor.models import MartorField
from taggit.managers import TaggableManager
from taggit.models import Tag

from notebooks.models import Notebook


class Note(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=255)
    description = MartorField()
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)
    notebook = models.ForeignKey(Notebook, on_delete=models.CASCADE)
    tags = TaggableManager(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class MyTag(models.Model):
    tag = models.OneToOneField(Tag, on_delete=models.CASCADE)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)


@receiver(post_save, sender=Tag)
def create_tag(sender, instance, created, **kwargs):
    if created:
        MyTag.objects.create(tag=instance)


@receiver(post_save, sender=Tag)
def save_tag(sender, instance, **kwargs):
    instance.mytag.save()

xqb/notebooks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    TemplateView,
    UpdateView,
)

from notebooks.models import Notebook


class NotebookCreateView(LoginRequiredMixin, CreateView):
    model = Notebook
    fields = ['name']

    def form_valid(self, form):
        form.instance.added_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('notebooks:notebook-list')


class NotebookListView(LoginRequiredMixin, ListView):
    model = Notebook
    context_object_name = 'notebooks'

    def get_queryset(self):
        return Notebook.objects.filter(added_by=self.request.user)


class NotebookUpdateView(LoginRequiredMixin, UpdateView):
    model = Notebook
    fields = [
        'name',
    ]
    template_name_suffix = '_update_form'

    def get_object(self):
        return get_object_or_404(
            Notebook, pk=self.kwargs['notebook_pk'], added_by=self.request.user
        )

    def get_success_url(self):
        return reverse('notebooks:notebook-list')


class NotebookDeleteView(LoginRequiredMixin, DeleteView):
    model = Notebook

    def get_object(self):
        return get_object_or_404(
            Notebook, pk=self.kwargs['notebook_pk'], added_by=self.request.user
        )

    def get_success_url(self):
        return reverse('notebooks:notebook-list')


class SearchNotebooksView(TemplateView):
    template_name = 'notebooks/searched_notebooks.html'

    def get_context_data(self, *args, **kwargs):
        search_query = self.request.GET.get('query')
        notebooks = Notebook.objects.filter(
            name__icontains=search_query, added_by=self.request.user
        )
        context = super().get_context_data(*args, **kwargs)
        context['notebooks'] = notebooks
        return context

xqb/notebooks/templates/notebooks/notebook_confirm_delete.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'notebooks/css/notebook_confirm_delete.css' %}">
{% endblock %}

{% block content %}
<div class="form-wrapper">
  <div class="form-header">
    Delete notebook
  </div>
  <form method="POST">
    {% csrf_token %}
    <div class="field-wrapper">
      <p>Are you sure you want to delete notebook "{{ object }}"?</p>
    </div>
    <div class="submit-button">
      <input type="submit" value="Confirm">
      <a href="{% url 'notebooks:notebook-list' %}">No, go back</a>
    </div>
  </form>
</div>
{% endblock %}

xqb/notebooks/templates/notebooks/notebook_form.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'notebooks/css/notebook_form.css' %}">
{% endblock %}

{% block content %}
<div class="form-wrapper">
  <div class="form-header">
    Create a new notebook
  </div>
  <form method="POST">
    {% csrf_token %}
    <div class="field-wrapper">
      <div class="name">
        {{ form.name.label_tag }}
        {{ form.name }}
        {{ form.name.errors }}
      </div>
    </div>
    <div class="submit-button">
      <input type="submit" value="Submit">
    </div>
  </form>
</div>
{% endblock %}

xqb/notebooks/templates/notebooks/notebook_list.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link href="{% static 'css/ffolders.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'notebooks/css/notebook_list.css' %}">
{% endblock %}

{% block js %}
<script src="{% url 'js_reverse' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
{% if notebooks %}
<div class="notebooks">
  {% for notebook in notebooks %}
  <a href="{% url 'notes:note-list' notebook.pk %}">
    <div class="ffolder medium cyan">
      <div class="notebook-info">
        <span>{{ notebook.name }}</span>
        <span class="note-count">{{ notebook.note_set.count }} items</span>    
      </div>
    </div>    
  </a>
  {% endfor %}
</div>
{% else %}
<div class="information">
  <div class="information-header">
    Info
  </div>
  <div class="information-wrapper">
    No notebooks yet.<br>
    <a href="{% url 'notebooks:notebook-create' %}">Create your first notebook!</a>
  </div>
</div>
{% endif %}
{% endblock %}

xqb/notebooks/templates/notebooks/notebook_update_form.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'notebooks/css/notebook_form.css' %}">
{% endblock %}

{% block content %}
<div class="form-wrapper">
  <div class="form-header">
    Update notebook
  </div>
  <form method="POST">
    {% csrf_token %}
    <div class="field-wrapper">
      <div class="name">
        {{ form.name.label_tag }}
        {{ form.name }}
        {{ form.name.errors }}
      </div>
    </div>
    <div class="submit-button">
      <input type="submit" value="Submit">
    </div>
  </form>
</div>
{% endblock %}