xqb/notebooks/urls.py
from django.urls import path

from notebooks.views import (
    NotebookCreateView,
    NotebookDeleteView,
    NotebookListView,
    NotebookUpdateView,
    SearchNotebooksView,
)


app_name = 'notebooks'
urlpatterns = [
    path('', NotebookListView.as_view(), name='notebook-list'),
    path('create/', NotebookCreateView.as_view(), name='notebook-create'),
    path('<int:notebook_pk>/delete/', NotebookDeleteView.as_view(), name='notebook-delete'),
    path('<int:notebook_pk>/update/', NotebookUpdateView.as_view(), name='notebook-update'),
    path('ajax/search/', SearchNotebooksView.as_view(), name='search-notebooks'),
]

xqb/notes/urls.py
from django.urls import path

from notes.views import (
    NoteCreateView,
    NoteDeleteView,
    NoteListView,
    NoteUpdateView,
    SearchNotesView,
    ShowNoteView,
)


app_name = 'notes'
urlpatterns = [
    path('<int:notebook_pk>/', NoteListView.as_view(), name='note-list'),
    path('create/', NoteCreateView.as_view(), name='note-create'),
    path('<int:notebook_pk>/create/', NoteCreateView.as_view(), name='note-create'),
    path('<int:notebook_pk>/<int:note_pk>/delete/', NoteDeleteView.as_view(), name='note-delete'),
    path('<int:notebook_pk>/<int:note_pk>/update/', NoteUpdateView.as_view(), name='note-update'),
    path('ajax/show-note/', ShowNoteView.as_view(), name='show-note'),
    path('ajax/search/<int:notebook_pk>/<str:by>/', SearchNotesView.as_view(), name='search-notes'),
]

xqb/users/urls.py
from django.urls import path
from django_registration.backends.activation.views import RegistrationView

from users.forms import NewRegistrationForm
from users.views import update_profile


app_name = 'users'
urlpatterns = [
    path('settings/', update_profile, name='settings'),
    path(
        'register/',
        RegistrationView.as_view(form_class=NewRegistrationForm),
        name='django_registration_register'
    ),
]

xqb/xqb/urls.py
from django.contrib import admin
from django.urls import include, path
from django_js_reverse.views import urls_js

from pages.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('users.urls')),
    path('jsreverse/', urls_js, name='js_reverse'),
    path('martor/', include('martor.urls')),
    path('notes/', include('notes.urls')),
    path('notebooks/', include('notebooks.urls')),
]

xqb/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>xqb</title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/base.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    {% block css %}
    {% endblock %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/sidebar.js' %}"></script>
    {% block js %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="sidebar">
            {% include 'sidebar.html' %}
        </div>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

xqb/templates/sidebar.html
<div class="sidebar">
    <nav>
      <ul class="menu">
          <li id="dashboard" class="no-submenu">
            <div class="menu-item">
              <span class="icon">Dashboard</span>
              <span></span>
            </div>
          </li>
          <li id="notes" class="has-submenu">
            <div class="menu-item">
                <span class="icon">Notes</span>
                <span class="arrow"></span>
            </div>
            <ul class="submenu">
                <li><a href="{% url 'notes:note-create' %}">New note</a></li>
                <li><a href="{% url 'notebooks:notebook-create' %}">New notebook</a></li>
                <li><a href="{% url 'notebooks:notebook-list' %}">View notebooks</a></li>
            </ul>
        </li>
        <li id="account" class="has-submenu">
          <div class="menu-item">
            <span class="icon">Account</span>
            <span class="arrow"></span>
          </div>
          {% if user.is_authenticated %}
          <ul class="submenu">
            <li><a href="{% url 'users:settings' %}">Settings</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
          {% else %}
          <ul class="submenu">
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'django_registration_register' %}">Register</a></li>
          </ul>
          {% endif %}
        </li>
      </ul>
    </nav>
  </div>